apiVersion: batch/v1
kind: CronJob
metadata:
  name: manage-slack-daily
spec:
  schedule: "21 21 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          containers:
          - name: manage-slack-daily
            image: localhost:5000/manage-slack-daily:latest
            command:
            - /bin/sh
            - -c
            - /app/daily
            env:
            - name: SLACK_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: common-secrets
                  key: SLACK_BOT_TOKEN
            - name: SLACK_CHANNEL_ID
              valueFrom:
                secretKeyRef:
                  name: common-secrets
                  key: SLACK_CHANNEL_ID
            - name: SLACK_USER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: common-secrets
                  key: SLACK_USER_TOKEN
          restartPolicy: Never
