# /etc/promtail/config.yml
server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://loki-svc:3100/loki/api/v1/push
scrape_configs:
  - job_name: varlogs
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/**/*log
  - job_name: messages
    static_configs:
      - targets:
          - localhost
        labels:
          job: messages
          __path__: /var/log/messages
  - job_name: journal # https://grafana.com/docs/loki/latest/send-data/promtail/configuration/#journal
    journal:
      path: /var/log/journal
      labels:
        job: "journal"
      relabel_configs:
        - source_labels: ['__journal__hostname']
          target_label: host
        - source_labels: ['__journal__systemd_unit']
          target_label: systemd_unit
          regex: '(.+)'
        - source_labels: ['__journal__systemd_user_unit']
          target_label: systemd_user_unit
          regex: '(.+)'
        - source_labels: ['__journal__transport']
          target_label: transport
          regex: '(.+)'
        - source_labels: ['__journal_priority_keyword']
          target_label: severity
          regex: '(.+)'
