apiVersion: batch/v1
kind: CronJob
metadata:
  name: tdnet
  namespace: tasks
spec:
  schedule: "37 11 * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          containers:
          - name: tdnet
            image: localhost:5000/tdnet:latest
            command:
            - /bin/sh
            - -c
            - |
              npm install
              npm run start
              export FILE_PATH=/app/tdnet/output.txt
              /app/slackPublisher
            volumeMounts:
            - mountPath: /app/tdnet/favorite.txt
              name: favoritelist
            env:
            - name: SLACK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: common-secrets
                  key: SLACK_BOT_TOKEN
            - name: SLACK_CHANNEL_ID
              valueFrom:
                secretKeyRef:
                  name: common-secrets
                  key: SLACK_CHANNEL
            - name: FAVORITES_FILE_PATH
              value: /app/tdnet/favorite.txt
            - name: FILE_OUTPUT
              value: true
          volumes:
          - name: favoritelist
            hostPath:
              path: /var/tmp/favorite.txt
              type: File
          restartPolicy: Never
