apiVersion: batch/v1
kind: CronJob
metadata:
  name: tdnet
  namespace: tasks
spec:
  schedule: "37 11 * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          containers:
            - name: tdnet
              image: localhost:5000/tdnet:latest
              command:
                - /bin/sh
                - -c
                - |
                  LOG=`npm install && npm run job`
                  if [ -e $FILE ]; then
                    export FILE_PATH=$FILE
                  else
                    export MESSAGE=$LOG
                  fi
                  echo $LOG
                  /app/slackPublisher
              volumeMounts:
                - mountPath: /app/tdnet/favorite.txt
                  name: favoritelist
              env:
                - name: SLACK_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: common-secrets
                      key: SLACK_BOT_TOKEN
                - name: SLACK_CHANNEL_ID
                  valueFrom:
                    secretKeyRef:
                      name: common-secrets
                      key: SLACK_CHANNEL_ID
                - name: FAVORITES_FILE_PATH
                  value: /app/tdnet/favorite.txt
                - name: FILE_OUTPUT
                  value: "true"
                - name: FILE
                  value: /app/tdnet/output.txt
          volumes:
            - name: favoritelist
              hostPath:
                path: /var/tmp/favorite.txt
                type: File
          restartPolicy: Never
