apiVersion: batch/v1
kind: CronJob
metadata:
  name: tdnet
  namespace: tasks
spec:
  schedule: "37 11 * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          containers:
          - name: tdnet
            image: localhost:5000/tdnet:latest
            command:
            - /bin/sh
            - -c
            - |
              npm install
              npm run start
              curl -F file=@output.txt -F "initial_comment=tdnet" -H "Authorization: Bearer $SLACK_BOT_TOKEN" -F "channels=$SLACK_CHANNEL" "https://slack.com/api/files.upload"
            volumeMounts:
            - mountPath: /app/tdnet/favorite.txt
              name: favoritelist
            env:
            - name: SLACK_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: common-secrets
                  key: SLACK_BOT_TOKEN
            - name: SLACK_CHANNEL
              valueFrom:
                secretKeyRef:
                  name: common-secrets
                  key: SLACK_CHANNEL
            - name: FAVORITES_FILE_PATH
              value: /app/tdnet/favorite.txt
          volumes:
          - name: favoritelist
            hostPath:
              path: /var/tmp/favorite.txt
              type: File
          restartPolicy: Never
