apiVersion: batch/v1
kind: CronJob
metadata:
  name: unitedcinemas
  namespace: tasks
spec:
  schedule: "37 3 * * 1"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          containers:
            - name: unitedcinemas
              image: localhost:5000/unitedcinemas:latest
              command:
                - /bin/sh
                - -c
                - |
                  LOG=`npm install && npm run job`
                  if [ -e $FILE ]; then
                    export FILE_PATH=$FILE
                  else
                    export MESSAGE=$LOG
                  fi
                  echo $LOG
                  /app/slackPublisher
              env:
                - name: SLACK_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: common-secrets
                      key: SLACK_BOT_TOKEN
                - name: SLACK_CHANNEL_ID
                  valueFrom:
                    secretKeyRef:
                      name: common-secrets
                      key: SLACK_CHANNEL_ID
                - name: THEATER
                  valueFrom:
                    secretKeyRef:
                      name: common-secrets
                      key: THEATER
                - name: FILE
                  value: /app/unitedcinemas/output.txt
          restartPolicy: Never
