apiVersion: batch/v1
kind: CronJob
metadata:
  name: count-commits-js
spec:
  schedule: "20 11 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: count-commits-js
            image: localhost:5000/count-commits-js
            command:
            - /bin/sh
            - -c
            - |
              export INSTALL_ID=`cat /etc/commonSecrets/INSTALL_ID`
              export APP_ID=`cat /etc/commonSecrets/APP_ID`
              cat /etc/commonSecrets/PRIVATE_KEY > /app/jwt/private-key.pem
              export GH_TOKEN=`/app/jwt`
              export GH_USER_NAME=`cat /etc/commonSecrets/GH_USER_NAME`
              export SLACK_BOT_TOKEN=`cat /etc/commonSecrets/SLACK_BOT_TOKEN`
              export SLACK_CHANNEL_ID=`cat /etc/commonSecrets/SLACK_CHANNEL_ID`
              /app/count-commits-js
            volumeMounts:
            - name: common-secrets
              mountPath: "/etc/commonSecrets"
              readOnly: true
          volumes:
          - name: common-secrets
            secret:
              secretName: common-secrets
          restartPolicy: Never
