apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  labels:
    app: alertmanager
  namespace: otel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      volumes:
      - name: alertmanager
        hostPath:
          path: /etc/alertmanager
          type: Directory
      containers:
      - name: alertmanager
        image: prom/alertmanager
        ports:
        - containerPort: 9093
        volumeMounts:
        - mountPath: /etc/alertmanager
          name: alertmanager
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-svc
  labels:
    run: alertmanager-svc
  namespace: otel
spec:
  ports:
  - port: 9093
    protocol: TCP
  selector:
    app: alertmanager
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-nodeport
  namespace: otel
spec:
  selector:
    app: alertmanager
  type: NodePort
  ports:
  - port: 9093
    nodePort: 30002
    protocol: TCP
