apiVersion: batch/v1
kind: CronJob
metadata:
  name: count-commits-js
spec:
  schedule: "20 20 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: alpine
            image: golang:1.21-alpine
            command:
            - /bin/sh
            - -c
            - |
              apk update
              apk add git
              git clone https://github.com/tkmsaaaam/count-commits-js.git
              cd count-commits-js
              go run main.go
            envFrom:
            - configMapRef:
                name: common-enviroments
          restartPolicy: Never
