apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
  namespace: otel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      volumes:
      - name: grafana-pv
        persistentVolumeClaim:
          claimName: grafana-pvc
      containers:
      - name: grafana
        image: docker.io/grafana/grafana@sha256:43b9c8b68a2cefcfe48770ced246a9b8f03cc8f790377f403ae979c5fefa9ca4
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-pv
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: otel
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
  namespace: otel
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  namespace: otel
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /var/lib/grafana
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  labels:
    run: grafana-svc
  namespace: otel
spec:
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: grafana
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-nodeport
  namespace: otel
spec:
  selector:
    app: grafana
  type: NodePort
  ports:
  - port: 3000
    nodePort: 30000
    protocol: TCP
