# https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/1d12566c29f8192bfaaabb72c3f2eca8df613a87/receiver/k8seventsreceiver/README.md
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-events-receiver
  labels:
    app: k8s-events-receiver
data:
  config.yaml: |
    receivers:
      k8s_events:
        namespaces: [default, otel, tasks]
    exporters:
      loki:
        endpoint: "http://loki-svc.otel.svc.cluster.local:3100/loki/api/v1/push"
    service:
      pipelines:
        logs:
          receivers: [k8s_events]
          exporters: [loki]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: k8s-events-receiver
  name: k8s-events-receiver
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-events-receiver
  labels:
    app: k8s-events-receiver
rules:
  - apiGroups:
      - ""
    resources:
      - events
      - namespaces
      - namespaces/status
      - nodes
      - nodes/spec
      - pods
      - pods/status
      - replicationcontrollers
      - replicationcontrollers/status
      - resourcequotas
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - daemonsets
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-events-receiver
  labels:
    app: k8s-events-receiver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-events-receiver
subjects:
  - kind: ServiceAccount
    name: k8s-events-receiver
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-events-receiver
  labels:
    app: k8s-events-receiver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-events-receiver
  template:
    metadata:
      labels:
        app: k8s-events-receiver
    spec:
      serviceAccountName: k8s-events-receiver
      containers:
        - name: k8s-events-receiver
          image: otel/opentelemetry-collector-contrib:latest
          args: ["--config", "/etc/config/config.yaml"]
          volumeMounts:
            - name: config
              mountPath: /etc/config
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 512Mi
      volumes:
        - name: config
          configMap:
            name: k8s-events-receiver
