apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: loki
        image: docker.io/grafana/loki@sha256:ffb77b674bd159de6c08f126e8fcc9121e035bde7fc05576d46d487282730bdf
        ports:
        - containerPort: 3100
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: loki-svc
  labels:
    run: loki-svc
spec:
  ports:
  - port: 3100
    protocol: TCP
  selector:
    app: loki
