apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  labels:
    app: loki
  namespace: otel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: loki
          image: docker.io/grafana/loki:latest
          ports:
            - containerPort: 3100
          resources:
            limits:
              cpu: 400m
              memory: 1024Mi
---
apiVersion: v1
kind: Service
metadata:
  name: loki-svc
  labels:
    run: loki-svc
  namespace: otel
spec:
  ports:
    - port: 3100
      protocol: TCP
  selector:
    app: loki
