apiVersion: batch/v1
kind: CronJob
metadata:
  name: manage-slack-daily
spec:
  schedule: "21 21 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: alpine
            image: golang:1.21-alpine
            command:
            - /bin/sh
            - -c
            - |
              apk update
              apk add git
              git clone https://github.com/tkmsaaaam/manage-slack.git
              cd manage-slack
              go run daily.go
            envFrom:
            - configMapRef:
                name: common-enviroments
          restartPolicy: Never
