apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-exporter
  labels:
    app: node-exporter
  namespace: otel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: node-exporter
          image: prom/node-exporter
          ports:
            - containerPort: 9100
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter-svc
  labels:
    run: node-exporter-svc
  namespace: otel
spec:
  ports:
    - port: 9100
      protocol: TCP
  selector:
    app: node-exporter
