apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-endpoints
  namespace: tasks
data:
  OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: "http://victoriametrics-svc.otel.svc.cluster.local:8428/opentelemetry/"
  OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: "http://victorialogs-svc.otel.svc.cluster.local:9428/insert/opentelemetry/"
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://victoriatraces-svc.otel.svc.cluster.local:10428/insert/opentelemetry"
