apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      volumes:
      - name: prometheus
        hostPath:
          path: /etc/prometheus
          type: Directory
      containers:
      - name: prometheus
        image: prom/prometheus
        ports:
        - containerPort: 9090
        volumeMounts:
        - mountPath: /etc/prometheus
          name: prometheus
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  labels:
    run: prometheus-svc
spec:
  ports:
  - port: 9090
    protocol: TCP
  selector:
    app: prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
spec:
  selector:
    app: prometheus
  type: NodePort
  ports:
  - port: 9090
    nodePort: 30001
    protocol: TCP
