apiVersion: apps/v1
kind: Deployment
metadata:
  name: promtail
  labels:
    app: promtail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      nodeSelector:
        kubernetes.io/hostname: raspberrypi
      volumes:
      - name: logs
        hostPath:
          path: /var/log
          type: Directory
      - name: config
        hostPath:
          path: /etc/promtail/config.yml
          type: File
      containers:
      - name: promtail
        image: grafana/promtail
        volumeMounts:
        - name: logs
          mountPath: /var/log
        - name: config
          mountPath: /etc/promtail/config.yml
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
