apiVersion: apps/v1
kind: Deployment
metadata:
  name: victoriatraces
  labels:
    app: victoriatraces
  namespace: otel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victoriatraces
  template:
    metadata:
      labels:
        app: victoriatraces
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: victoriatraces
          image: docker.io/victoriametrics/victoria-traces:v0.10.0 # https://github.com/VictoriaMetrics/victoriaTraces/releases https://hub.docker.com/r/victoriametrics/victoria-traces
          ports:
            - containerPort: 10428
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 1000m
              memory: 1536Mi
---
apiVersion: v1
kind: Service
metadata:
  name: victoriatraces-svc
  labels:
    run: victoriatraces-svc
  namespace: otel
spec:
  ports:
    - port: 10428
      protocol: TCP
  selector:
    app: victoriatraces
# TODO: persistent volume
