apiVersion: apps/v1
kind: Deployment
metadata:
  name: victorialogs
  labels:
    app: victorialogs
  namespace: otel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victorialogs
  template:
    metadata:
      labels:
        app: victorialogs
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: victorialogs
          image: docker.io/victoriametrics/victoria-logs:v1.52.0 # https://github.com/VictoriaMetrics/VictoriaLogs/releases https://hub.docker.com/r/victoriametrics/victoria-logs
          ports:
            - containerPort: 9428
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 1000m
              memory: 1536Mi
---
apiVersion: v1
kind: Service
metadata:
  name: victorialogs-svc
  labels:
    run: victorialogs-svc
  namespace: otel
spec:
  ports:
    - port: 9428
      protocol: TCP
  selector:
    app: victorialogs
# TODO: persistent volume
