apiVersion: batch/v1
kind: CronJob
metadata:
  name: weather-notification
spec:
  schedule: "07 03 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: alpine
            image: golang:1.21-alpine
            command:
            - /bin/sh
            - -c
            - |
              apk update
              apk add curl
              curl https://github.com/tkmsaaaam/weather-notification/archive/refs/heads/main.tar.gz -OL
              tar -zxvf main.tar.gz
              rm -rf main.tar.gz
              cd weather-notification-main
              export CITY_ID=`cat /etc/commonSecrets/CITY_ID`
              export SLACK_BOT_TOKEN=`cat /etc/commonSecrets/SLACK_BOT_TOKEN`
              export SLACK_CHANNEL_ID=`cat /etc/commonSecrets/SLACK_CHANNEL_ID`
              go run main.go
            volumeMounts:
            - name: common-secrets
              mountPath: "/etc/commonSecrets"
              readOnly: true
          volumes:
          - name: common-secrets
            secret:
              secretName: common-secrets
          restartPolicy: Never
