apiVersion: batch/v1
kind: CronJob
metadata:
  name: manage-slack-main
spec:
  schedule: "43 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          containers:
          - name: manage-slack-main
            image: localhost:5000/manage-slack-main:latest
            command:
            - /bin/sh
            - -c
            - |
              export SLACK_BOT_TOKEN=`cat /etc/commonSecrets/SLACK_BOT_TOKEN`
              export SLACK_CHANNEL_ID=`cat /etc/commonSecrets/SLACK_CHANNEL_ID`
              export SLACK_USER_TOKEN=`cat /etc/commonSecrets/SLACK_USER_TOKEN`
              /app/main
            env:
            - name: DAYS
              value: "3"
            volumeMounts:
            - name: common-secrets
              mountPath: "/etc/commonSecrets"
              readOnly: true
          volumes:
          - name: common-secrets
            secret:
              secretName: common-secrets
          restartPolicy: Never
