apiVersion: batch/v1
kind: CronJob
metadata:
  name: manage-slack-main
spec:
  schedule: "43 * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          containers:
          - name: manage-slack-main
            image: localhost:5000/manage-slack-main:latest
            command:
            - /bin/sh
            - -c
            - /app/main
            env:
            - name: DAYS
              value: "3"
            - name: SLACK_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: common-secrets
                  key: SLACK_BOT_TOKEN
            - name: SLACK_CHANNEL_ID
              valueFrom:
                secretKeyRef:
                  name: common-secrets
                  key: SLACK_CHANNEL_ID
            - name: SLACK_USER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: common-secrets
                  key: SLACK_USER_TOKEN
          restartPolicy: Never
