# /etc/prometheus/prometheus.yml
# https://prometheus.io/docs/prometheus/latest/configuration/configuration/
global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
          - localhost:9090
  - job_name: node-exporter
    static_configs:
      - targets:
          - node-exporter-svc:9100
  - job_name: cadvisor
    static_configs:
      - targets:
          - cadvisor-svc.cadvisor.svc.cluster.local:8080
  - job_name: k8s-cluster-receiver
    static_configs:
      - targets:
          - k8s-cluster-receiver-svc.default.svc.cluster.local:8889
  - job_name: pushgateway
    static_configs:
      - targets:
          - pushgateway-svc:9091
