apiVersion: batch/v1
kind: CronJob
metadata:
  name: rakuten-sec
  namespace: tasks
spec:
  schedule: "37 20 * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          containers:
            - name: rakuten-sec
              image: localhost:5000/rakuten-sec:latest
              command:
                - /bin/sh
                - -c
                - |
                  LOG=`npm install && npm run job`
                  if [ -e $FILE ]; then
                    export FILE_PATH=$FILE
                  else
                    export MESSAGE=$LOG
                  fi
                  echo $LOG
                  /app/slackPublisher
              env:
                - name: USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: common-secrets
                      key: RAKUTEN_USERNAME
                - name: PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: common-secrets
                      key: RAKUTEN_PASSWORD
                - name: SLACK_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: common-secrets
                      key: SLACK_BOT_TOKEN
                - name: SLACK_CHANNEL_ID
                  valueFrom:
                    secretKeyRef:
                      name: common-secrets
                      key: SLACK_CHANNEL_ID
                - name: FILE
                  value: /app/rakuten-sec/output.txt
              resources:
                limits:
                  cpu: 800m
                  memory: 1024Mi
          restartPolicy: Never
