apiVersion: batch/v1
kind: CronJob
metadata:
  name: check-login
spec:
  schedule: "55 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: alpine
            image: localhost:5000/check-login
            command:
            - /bin/sh
            - -c
            - |
              RESULT=`/app/AuthlogParser`
              COUNT=`echo -n "$RESULT" | wc -l`
              TEXT="ログイン履歴"$'\n'"行数は$COUNT"$'\n'"$RESULT"
              export SLACK_TOKEN=`cat /etc/commonSecrets/SLACK_TOKEN`
              export SLACK_CHANNEL=`cat /etc/commonSecrets/SLACK_CHANNEL`
              curl -H "Authorization: Bearer $SLACK_TOKEN" -d "text=$TEXT" -d "channel=$SLACK_CHANNEL" "https://slack.com/api/chat.postMessage"
            volumeMounts:
            - mountPath: /logs/auth.log
              name: authlog
              readOnly: true
            - name: common-secrets
              mountPath: "/etc/commonSecrets"
              readOnly: true
            env:
            - name: TZ
              value: Asia/Tokyo
            - name: LANG
              value: C.UTF-8
            - name: LANGUAGE
              value: en_US
          volumes:
          - name: authlog
            hostPath:
              path: /var/log/auth.log
              type: File
          - name: common-secrets
            secret:
              secretName: common-secrets
          restartPolicy: Never
      backoffLimit: 2
