apiVersion: batch/v1
kind: CronJob
metadata:
  name: check-login
  namespace: tasks
spec:
  schedule: "55 * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          containers:
            - name: check-login
              image: localhost:5000/check-login:latest
              command:
                - /bin/sh
                - -c
                - |
                  RESULT=`./AuthlogParser | jq`
                  export MESSAGE="ログイン履歴: $RESULT"
                  /app/slackPublisher
              volumeMounts:
                - mountPath: /logs/auth.log
                  name: authlog
                  readOnly: true
              env:
                - name: TZ
                  value: Asia/Tokyo
                - name: LANG
                  value: C.UTF-8
                - name: LANGUAGE
                  value: en_US
                - name: SLACK_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: common-secrets
                      key: SLACK_BOT_TOKEN
                - name: SLACK_CHANNEL_ID
                  valueFrom:
                    secretKeyRef:
                      name: common-secrets
                      key: SLACK_CHANNEL_ID
                - name: HOSTNAME
                  valueFrom:
                    secretKeyRef:
                      name: common-secrets
                      key: HOSTNAME
          volumes:
            - name: authlog
              hostPath:
                path: /var/log/auth.log
                type: File
          restartPolicy: Never
