apiVersion: batch/v1
kind: CronJob
metadata:
  name: weather-notification
spec:
  schedule: "07 18 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          containers:
          - name: weather-notification
            image: localhost:5000/weather-notification:latest
            command:
            - /bin/sh
            - -c
            - |
              export CITY_ID=`cat /etc/commonSecrets/CITY_ID`
              export SLACK_BOT_TOKEN=`cat /etc/commonSecrets/SLACK_BOT_TOKEN`
              export SLACK_CHANNEL_ID=`cat /etc/commonSecrets/SLACK_CHANNEL_ID`
              /app/weather-notification
            volumeMounts:
            - name: common-secrets
              mountPath: "/etc/commonSecrets"
              readOnly: true
          volumes:
          - name: common-secrets
            secret:
              secretName: common-secrets
          restartPolicy: Never
